# Generated by Django 5.2.1 on 2025-05-10 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_count', models.PositiveIntegerField()),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Sales Snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('entry_point', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False)),
                ('conversion_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('first_product_view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productapp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Behavior',
                'indexes': [models.Index(fields=['-timestamp'], name='analyticsap_timesta_28138b_idx'), models.Index(fields=['converted'], name='analyticsap_convert_8b7eb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('cart_additions', models.PositiveIntegerField(default=0)),
                ('purchases', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
            ],
            options={
                'ordering': ['-date', '-revenue'],
                'indexes': [models.Index(fields=['-date', 'revenue'], name='analyticsap_date_516b56_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
